### ISSUE TITLE
Possible to parameterize version of gpb?

### ISSUE THREAD

**Issue by tomas-abrahamsson** [lrascao/rebar3_gpb_plugin#40]
A curious question: Is it possible for the user of rebar3_gpb_plugin to parameterize the version of gpb? In the rebar.config or somewhere else if there's a more appropriate place?

I was thinking this could lead both to you not having to cut a new release every time I make a new version of gpb, and also that one particular use-case might be a little bit easier: for the user to see what actual version of gpb (or some other plugin-provided dependency) is used. It could be right in the rebar.config file (or wherever), whereas right now they might need to know that rebar3_gpb_plugin 1.10.4 maps to gpb 3.26.8.

Another use-case that might perhaps be a little more difficult would be for rebar3_gpb_plugin to have a sensible default. Maybe `latest` or perhaps `master` could do.

Maybe this is more of a question for rebar3 than for rebar3_gpb_plugin, although this particular plugin is of interest to me, of course :)

I should also say that for me, it is absolutely totally no problem at all to continue sending pull requests, I've automated it in a script, so it's no burden at all, I was just curious about possible alternatives.

**Comment by lrascao** [comment]
I don't mind keeping the current scheme of things, i also have it tuned already to take me less than 1m each time.
The user is not forced to use the plugin's version of gpb, he can pin a specific one at a higher rebar.config, i suppose we could have a way of using the rebar.config.script functionality to override the plugin's version, but since nobody asked this up until time i guess we can wait until the need arises.

**Comment by tomas-abrahamsson** [comment]
Yes, sensible to wait until there's a real need for such things. I'll close this issue, my main aim with this issue was airing the idea, which has now been done :)
